In [1]:
# Necessary imports
import numpy as np
import pandas as pd

from utils.load_dataset import load_dataset
from utils.split_x_y import split_x_y
from utils.under_sampling import random_under_sampling, near_miss_under_sampling
from utils.over_sampling import random_over_sampling
from utils.smote import smote_nc
from utils.save_dataset import save_dataset

In [2]:
# Load dataframes
train_df_one = load_dataset(dataset_type='train', encoding='oe', balance=1)
train_df_three = load_dataset(dataset_type='train', encoding='oe', balance=3)
train_df_five = load_dataset(dataset_type='train', encoding='oe', balance=5)
train_df_twenty_five = load_dataset(dataset_type='train', encoding='oe', balance=25)
train_df_fifty = load_dataset(dataset_type='train', encoding='oe', balance=50)

In [3]:
# Sanity check for correct loading
print(train_df_one.info())
print(train_df_three.info())
print(train_df_five.info())
print(train_df_twenty_five.info())
print(train_df_fifty.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 15152 entries, 27 to 481067
Data columns (total 12 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   itemID                        15152 non-null  float64
 1   size                          15152 non-null  float64
 2   color                         15152 non-null  float64
 3   manufacturerID                15152 non-null  float64
 4   price                         15152 non-null  float64
 5   customerID                    15152 non-null  float64
 6   salutation                    15152 non-null  float64
 7   state                         15152 non-null  float64
 8   returnShipment                15152 non-null  int64
 9   deliveryTime                  15152 non-null  int64
 10  ageOfAccountUntilTimeOfOrder  15152 non-null  int64
 11  age                           15152 non-null  int64
dtypes: float64(8), int64(4)
memory usage: 1.5 MB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 15464 entries, 27 to 481047
Data columns (total 12 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   itemID                        15464 non-null  float64
 1   size                          15464 non-null  float64
 2   color                         15464 non-null  float64
 3   manufacturerID                15464 non-null  float64
 4   price                         15464 non-null  float64
 5   customerID                    15464 non-null  float64
 6   salutation                    15464 non-null  float64
 7   state                         15464 non-null  float64
 8   returnShipment                15464 non-null  int64
 9   deliveryTime                  15464 non-null  int64
 10  ageOfAccountUntilTimeOfOrder  15464 non-null  int64
 11  age                           15464 non-null  int64
dtypes: float64(8), int64(4)
memory usage: 1.5 MB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 15789 entries, 27 to 481047
Data columns (total 12 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   itemID                        15789 non-null  float64
 1   size                          15789 non-null  float64
 2   color                         15789 non-null  float64
 3   manufacturerID                15789 non-null  float64
 4   price                         15789 non-null  float64
 5   customerID                    15789 non-null  float64
 6   salutation                    15789 non-null  float64
 7   state                         15789 non-null  float64
 8   returnShipment                15789 non-null  int64
 9   deliveryTime                  15789 non-null  int64
 10  ageOfAccountUntilTimeOfOrder  15789 non-null  int64
 11  age                           15789 non-null  int64
dtypes: float64(8), int64(4)
memory usage: 1.6 MB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 20000 entries, 27 to 481066
Data columns (total 12 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   itemID                        20000 non-null  float64
 1   size                          20000 non-null  float64
 2   color                         20000 non-null  float64
 3   manufacturerID                20000 non-null  float64
 4   price                         20000 non-null  float64
 5   customerID                    20000 non-null  float64
 6   salutation                    20000 non-null  float64
 7   state                         20000 non-null  float64
 8   returnShipment                20000 non-null  int64
 9   deliveryTime                  20000 non-null  int64
 10  ageOfAccountUntilTimeOfOrder  20000 non-null  int64
 11  age                           20000 non-null  int64
dtypes: float64(8), int64(4)
memory usage: 2.0 MB
None
<class 'pandas.core.frame.DataFrame'>
Int64Index: 30000 entries, 16 to 481067
Data columns (total 12 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   itemID                        30000 non-null  float64
 1   size                          30000 non-null  float64
 2   color                         30000 non-null  float64
 3   manufacturerID                30000 non-null  float64
 4   price                         30000 non-null  float64
 5   customerID                    30000 non-null  float64
 6   salutation                    30000 non-null  float64
 7   state                         30000 non-null  float64
 8   returnShipment                30000 non-null  int64
 9   deliveryTime                  30000 non-null  int64
 10  ageOfAccountUntilTimeOfOrder  30000 non-null  int64
 11  age                           30000 non-null  int64
dtypes: float64(8), int64(4)
memory usage: 3.0 MB
None

In [4]:
# Random under sampling
# Random Under sampling aims to balance class distribution by randomly eliminating majority class examples.
# This is done until majority and minority class instances are balanced out.

# 1% class balance
train_one_X_random_under, train_one_y_random_under = random_under_sampling(df=train_df_one, target='returnShipment')

# 3% class balance
train_three_X_random_under, train_three_y_random_under = random_under_sampling(df=train_df_three, target='returnShipment')

# 5% class balance
train_five_X_random_under, train_five_y_random_under = random_under_sampling(df=train_df_five, target='returnShipment')

# 25% class balance
train_twenty_five_X_random_under, train_twenty_five_y_random_under = random_under_sampling(df=train_df_twenty_five, target='returnShipment')

# 50% class balance
train_fifty_X_random_under, train_fifty_y_random_under = random_under_sampling(df=train_df_fifty, target='returnShipment')

In [5]:
# Checking new dataframes
print(train_one_X_random_under.info())
print(train_one_y_random_under.value_counts())

print(train_three_X_random_under.info())
print(train_three_y_random_under.value_counts())

print(train_five_X_random_under.info())
print(train_five_y_random_under.value_counts())

print(train_twenty_five_X_random_under.info())
print(train_twenty_five_y_random_under.value_counts())

print(train_fifty_X_random_under.info())
print(train_fifty_y_random_under.value_counts())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 304 entries, 0 to 303
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   itemID                        304 non-null    float64
 1   size                          304 non-null    float64
 2   color                         304 non-null    float64
 3   manufacturerID                304 non-null    float64
 4   price                         304 non-null    float64
 5   customerID                    304 non-null    float64
 6   salutation                    304 non-null    float64
 7   state                         304 non-null    float64
 8   deliveryTime                  304 non-null    int64
 9   ageOfAccountUntilTimeOfOrder  304 non-null    int64
 10  age                           304 non-null    int64
dtypes: float64(8), int64(3)
memory usage: 26.2 KB
None
returnShipment
0                 152
1                 152
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 928 entries, 0 to 927
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   itemID                        928 non-null    float64
 1   size                          928 non-null    float64
 2   color                         928 non-null    float64
 3   manufacturerID                928 non-null    float64
 4   price                         928 non-null    float64
 5   customerID                    928 non-null    float64
 6   salutation                    928 non-null    float64
 7   state                         928 non-null    float64
 8   deliveryTime                  928 non-null    int64
 9   ageOfAccountUntilTimeOfOrder  928 non-null    int64
 10  age                           928 non-null    int64
dtypes: float64(8), int64(3)
memory usage: 79.9 KB
None
returnShipment
0                 464
1                 464
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1578 entries, 0 to 1577
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   itemID                        1578 non-null   float64
 1   size                          1578 non-null   float64
 2   color                         1578 non-null   float64
 3   manufacturerID                1578 non-null   float64
 4   price                         1578 non-null   float64
 5   customerID                    1578 non-null   float64
 6   salutation                    1578 non-null   float64
 7   state                         1578 non-null   float64
 8   deliveryTime                  1578 non-null   int64
 9   ageOfAccountUntilTimeOfOrder  1578 non-null   int64
 10  age                           1578 non-null   int64
dtypes: float64(8), int64(3)
memory usage: 135.7 KB
None
returnShipment
0                 789
1                 789
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   itemID                        10000 non-null  float64
 1   size                          10000 non-null  float64
 2   color                         10000 non-null  float64
 3   manufacturerID                10000 non-null  float64
 4   price                         10000 non-null  float64
 5   customerID                    10000 non-null  float64
 6   salutation                    10000 non-null  float64
 7   state                         10000 non-null  float64
 8   deliveryTime                  10000 non-null  int64
 9   ageOfAccountUntilTimeOfOrder  10000 non-null  int64
 10  age                           10000 non-null  int64
dtypes: float64(8), int64(3)
memory usage: 859.5 KB
None
returnShipment
0                 5000
1                 5000
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   itemID                        30000 non-null  float64
 1   size                          30000 non-null  float64
 2   color                         30000 non-null  float64
 3   manufacturerID                30000 non-null  float64
 4   price                         30000 non-null  float64
 5   customerID                    30000 non-null  float64
 6   salutation                    30000 non-null  float64
 7   state                         30000 non-null  float64
 8   deliveryTime                  30000 non-null  int64
 9   ageOfAccountUntilTimeOfOrder  30000 non-null  int64
 10  age                           30000 non-null  int64
dtypes: float64(8), int64(3)
memory usage: 2.5 MB
None
returnShipment
0                 15000
1                 15000
dtype: int64

In [6]:
# Save new datasets
train_one_random_under = pd.concat([train_one_X_random_under, train_one_y_random_under], axis=1)
save_dataset(df=train_one_random_under, dataset_type='train', balance=1, technique='ru', encoding='oe')

train_three_random_under = pd.concat([train_three_X_random_under, train_three_y_random_under], axis=1)
save_dataset(df=train_three_random_under, dataset_type='train', balance=3, technique='ru', encoding='oe')

train_five_random_under = pd.concat([train_five_X_random_under, train_five_y_random_under], axis=1)
save_dataset(df=train_five_random_under, dataset_type='train', balance=5, technique='ru', encoding='oe')

train_twenty_five_random_under = pd.concat([train_twenty_five_X_random_under, train_twenty_five_y_random_under], axis=1)
save_dataset(df=train_twenty_five_random_under, dataset_type='train', balance=25, technique='ru', encoding='oe')

train_fifty_random_under = pd.concat([train_fifty_X_random_under, train_fifty_y_random_under], axis=1)
save_dataset(df=train_fifty_random_under, dataset_type='train', balance=50, technique='ru', encoding='oe')

In [7]:
# Near Miss under sampling
# NearMiss refers to a collection of under-sampling methods that select examples based on the distance of majority
# class examples to minority class examples.

# 1% class balance
train_one_X_near_miss_under, train_one_y_near_miss_under = near_miss_under_sampling(df=train_df_one, target='returnShipment')

# 3% class balance
train_three_X_near_miss_under, train_three_y_near_miss_under = near_miss_under_sampling(df=train_df_three, target='returnShipment')

# 5% class balance
train_five_X_near_miss_under, train_five_y_near_miss_under = near_miss_under_sampling(df=train_df_five, target='returnShipment')

# 25% class balance
train_twenty_five_X_near_miss_under, train_twenty_five_y_near_miss_under = near_miss_under_sampling(df=train_df_twenty_five, target='returnShipment')

# 50% class balance
train_fifty_X_near_miss_under, train_fifty_y_near_miss_under = near_miss_under_sampling(df=train_df_fifty, target='returnShipment')

In [8]:
# Checking new dataframes
print(train_one_X_near_miss_under.info())
print(train_one_y_near_miss_under.value_counts())

print(train_three_X_near_miss_under.info())
print(train_three_y_near_miss_under.value_counts())

print(train_five_X_near_miss_under.info())
print(train_five_y_near_miss_under.value_counts())

print(train_twenty_five_X_near_miss_under.info())
print(train_twenty_five_y_near_miss_under.value_counts())

print(train_fifty_X_near_miss_under.info())
print(train_fifty_y_near_miss_under.value_counts())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 304 entries, 0 to 303
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   itemID                        304 non-null    float64
 1   size                          304 non-null    float64
 2   color                         304 non-null    float64
 3   manufacturerID                304 non-null    float64
 4   price                         304 non-null    float64
 5   customerID                    304 non-null    float64
 6   salutation                    304 non-null    float64
 7   state                         304 non-null    float64
 8   deliveryTime                  304 non-null    int64
 9   ageOfAccountUntilTimeOfOrder  304 non-null    int64
 10  age                           304 non-null    int64
dtypes: float64(8), int64(3)
memory usage: 26.2 KB
None
returnShipment
0                 152
1                 152
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 928 entries, 0 to 927
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   itemID                        928 non-null    float64
 1   size                          928 non-null    float64
 2   color                         928 non-null    float64
 3   manufacturerID                928 non-null    float64
 4   price                         928 non-null    float64
 5   customerID                    928 non-null    float64
 6   salutation                    928 non-null    float64
 7   state                         928 non-null    float64
 8   deliveryTime                  928 non-null    int64
 9   ageOfAccountUntilTimeOfOrder  928 non-null    int64
 10  age                           928 non-null    int64
dtypes: float64(8), int64(3)
memory usage: 79.9 KB
None
returnShipment
0                 464
1                 464
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1578 entries, 0 to 1577
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   itemID                        1578 non-null   float64
 1   size                          1578 non-null   float64
 2   color                         1578 non-null   float64
 3   manufacturerID                1578 non-null   float64
 4   price                         1578 non-null   float64
 5   customerID                    1578 non-null   float64
 6   salutation                    1578 non-null   float64
 7   state                         1578 non-null   float64
 8   deliveryTime                  1578 non-null   int64
 9   ageOfAccountUntilTimeOfOrder  1578 non-null   int64
 10  age                           1578 non-null   int64
dtypes: float64(8), int64(3)
memory usage: 135.7 KB
None
returnShipment
0                 789
1                 789
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   itemID                        10000 non-null  float64
 1   size                          10000 non-null  float64
 2   color                         10000 non-null  float64
 3   manufacturerID                10000 non-null  float64
 4   price                         10000 non-null  float64
 5   customerID                    10000 non-null  float64
 6   salutation                    10000 non-null  float64
 7   state                         10000 non-null  float64
 8   deliveryTime                  10000 non-null  int64
 9   ageOfAccountUntilTimeOfOrder  10000 non-null  int64
 10  age                           10000 non-null  int64
dtypes: float64(8), int64(3)
memory usage: 859.5 KB
None
returnShipment
0                 5000
1                 5000
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   itemID                        30000 non-null  float64
 1   size                          30000 non-null  float64
 2   color                         30000 non-null  float64
 3   manufacturerID                30000 non-null  float64
 4   price                         30000 non-null  float64
 5   customerID                    30000 non-null  float64
 6   salutation                    30000 non-null  float64
 7   state                         30000 non-null  float64
 8   deliveryTime                  30000 non-null  int64
 9   ageOfAccountUntilTimeOfOrder  30000 non-null  int64
 10  age                           30000 non-null  int64
dtypes: float64(8), int64(3)
memory usage: 2.5 MB
None
returnShipment
0                 15000
1                 15000
dtype: int64

In [9]:
# Save new datasets
train_one_near_miss_under = pd.concat([train_one_X_near_miss_under, train_one_y_near_miss_under], axis=1)
save_dataset(df=train_one_near_miss_under, dataset_type='train', balance=1, technique='nmu', encoding='oe')

train_three_near_miss_under = pd.concat([train_three_X_near_miss_under, train_three_y_near_miss_under], axis=1)
save_dataset(df=train_three_near_miss_under, dataset_type='train', balance=3, technique='nmu', encoding='oe')

train_five_near_miss_under = pd.concat([train_five_X_near_miss_under, train_five_y_near_miss_under], axis=1)
save_dataset(df=train_five_near_miss_under, dataset_type='train', balance=5, technique='nmu', encoding='oe')

train_twenty_five_near_miss_under = pd.concat([train_twenty_five_X_near_miss_under, train_twenty_five_y_near_miss_under], axis=1)
save_dataset(df=train_twenty_five_near_miss_under, dataset_type='train', balance=25, technique='nmu', encoding='oe')

train_fifty_near_miss_under = pd.concat([train_fifty_X_near_miss_under, train_fifty_y_near_miss_under], axis=1)
save_dataset(df=train_fifty_near_miss_under, dataset_type='train', balance=50, technique='nmu', encoding='oe')

In [10]:
# Random Over Sampling
# Over-Sampling increases the number of instances in the minority class by randomly replicating them in order 
# to present a higher representation of the minority class in the sample. 

# 1% class balance
train_one_X_random_over, train_one_y_random_over = random_over_sampling(df=train_df_one, target='returnShipment')

# 3% class balance
train_three_X_random_over, train_three_y_random_over = random_over_sampling(df=train_df_three, target='returnShipment')

# 5% class balance
train_five_X_random_over, train_five_y_random_over = random_over_sampling(df=train_df_five, target='returnShipment')

# 25% class balance
train_twenty_five_X_random_over, train_twenty_five_y_random_over = random_over_sampling(df=train_df_twenty_five, target='returnShipment')

# 50% class balance
train_fifty_X_random_over, train_fifty_y_random_over = random_over_sampling(df=train_df_fifty, target='returnShipment')

In [11]:
# Checking new dataframes
print(train_one_X_random_over.info())
print(train_one_y_random_over.value_counts())

print(train_three_X_random_over.info())
print(train_three_y_random_over.value_counts())

print(train_five_X_random_over.info())
print(train_five_y_random_over.value_counts())

print(train_twenty_five_X_random_over.info())
print(train_twenty_five_y_random_over.value_counts())

print(train_fifty_X_random_over.info())
print(train_fifty_y_random_over.value_counts())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   itemID                        30000 non-null  float64
 1   size                          30000 non-null  float64
 2   color                         30000 non-null  float64
 3   manufacturerID                30000 non-null  float64
 4   price                         30000 non-null  float64
 5   customerID                    30000 non-null  float64
 6   salutation                    30000 non-null  float64
 7   state                         30000 non-null  float64
 8   deliveryTime                  30000 non-null  int64
 9   ageOfAccountUntilTimeOfOrder  30000 non-null  int64
 10  age                           30000 non-null  int64
dtypes: float64(8), int64(3)
memory usage: 2.5 MB
None
returnShipment
0                 15000
1                 15000
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   itemID                        30000 non-null  float64
 1   size                          30000 non-null  float64
 2   color                         30000 non-null  float64
 3   manufacturerID                30000 non-null  float64
 4   price                         30000 non-null  float64
 5   customerID                    30000 non-null  float64
 6   salutation                    30000 non-null  float64
 7   state                         30000 non-null  float64
 8   deliveryTime                  30000 non-null  int64
 9   ageOfAccountUntilTimeOfOrder  30000 non-null  int64
 10  age                           30000 non-null  int64
dtypes: float64(8), int64(3)
memory usage: 2.5 MB
None
returnShipment
0                 15000
1                 15000
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   itemID                        30000 non-null  float64
 1   size                          30000 non-null  float64
 2   color                         30000 non-null  float64
 3   manufacturerID                30000 non-null  float64
 4   price                         30000 non-null  float64
 5   customerID                    30000 non-null  float64
 6   salutation                    30000 non-null  float64
 7   state                         30000 non-null  float64
 8   deliveryTime                  30000 non-null  int64
 9   ageOfAccountUntilTimeOfOrder  30000 non-null  int64
 10  age                           30000 non-null  int64
dtypes: float64(8), int64(3)
memory usage: 2.5 MB
None
returnShipment
0                 15000
1                 15000
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   itemID                        30000 non-null  float64
 1   size                          30000 non-null  float64
 2   color                         30000 non-null  float64
 3   manufacturerID                30000 non-null  float64
 4   price                         30000 non-null  float64
 5   customerID                    30000 non-null  float64
 6   salutation                    30000 non-null  float64
 7   state                         30000 non-null  float64
 8   deliveryTime                  30000 non-null  int64
 9   ageOfAccountUntilTimeOfOrder  30000 non-null  int64
 10  age                           30000 non-null  int64
dtypes: float64(8), int64(3)
memory usage: 2.5 MB
None
returnShipment
0                 15000
1                 15000
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   itemID                        30000 non-null  float64
 1   size                          30000 non-null  float64
 2   color                         30000 non-null  float64
 3   manufacturerID                30000 non-null  float64
 4   price                         30000 non-null  float64
 5   customerID                    30000 non-null  float64
 6   salutation                    30000 non-null  float64
 7   state                         30000 non-null  float64
 8   deliveryTime                  30000 non-null  int64
 9   ageOfAccountUntilTimeOfOrder  30000 non-null  int64
 10  age                           30000 non-null  int64
dtypes: float64(8), int64(3)
memory usage: 2.5 MB
None
returnShipment
0                 15000
1                 15000
dtype: int64

In [12]:
# Save new datasets
train_one_random_over = pd.concat([train_one_X_random_over, train_one_y_random_over], axis=1)
save_dataset(df=train_one_random_over, dataset_type='train', balance=1, technique='ro', encoding='oe')

train_three_random_over = pd.concat([train_three_X_random_over, train_three_y_random_over], axis=1)
save_dataset(df=train_three_random_over, dataset_type='train', balance=3, technique='ro', encoding='oe')

train_five_random_over = pd.concat([train_five_X_random_over, train_five_y_random_over], axis=1)
save_dataset(df=train_five_random_over, dataset_type='train', balance=5, technique='ro', encoding='oe')

train_twenty_five_random_over = pd.concat([train_twenty_five_X_random_over, train_twenty_five_y_random_over], axis=1)
save_dataset(df=train_twenty_five_random_over, dataset_type='train', balance=25, technique='ro', encoding='oe')

train_fifty_random_over = pd.concat([train_fifty_X_random_over, train_fifty_y_random_over], axis=1)
save_dataset(df=train_fifty_random_over, dataset_type='train', balance=50, technique='ro', encoding='oe')

In [13]:
# SMOTE

# Indices of categorical features
categorical_features = [0, 1, 2, 3, 5, 6, 7]

# 1% class balance
train_one_X_smote, train_one_y_smote = smote_nc(df=train_df_one, target='returnShipment', categorical_features=categorical_features)

# 3% class balance
train_three_X_smote, train_three_y_smote = smote_nc(df=train_df_three, target='returnShipment', categorical_features=categorical_features)

# 5% class balance
train_five_X_smote, train_five_y_smote = smote_nc(df=train_df_five, target='returnShipment', categorical_features=categorical_features)

# 25% class balance
train_twenty_five_X_smote, train_twenty_five_y_smote = smote_nc(df=train_df_twenty_five, target='returnShipment', categorical_features=categorical_features)

# 50% class balance
train_fifty_X_smote, train_fifty_y_smote = smote_nc(df=train_df_fifty, target='returnShipment', categorical_features=categorical_features)

In [14]:
# Checking new dataframes
print(train_one_X_smote.info())
print(train_one_y_smote.value_counts())

print(train_three_X_smote.info())
print(train_three_y_smote.value_counts())

print(train_five_X_smote.info())
print(train_five_y_smote.value_counts())

print(train_twenty_five_X_smote.info())
print(train_twenty_five_y_smote.value_counts())

print(train_fifty_X_smote.info())
print(train_fifty_y_smote.value_counts())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   itemID                        30000 non-null  float64
 1   size                          30000 non-null  float64
 2   color                         30000 non-null  float64
 3   manufacturerID                30000 non-null  float64
 4   price                         30000 non-null  float64
 5   customerID                    30000 non-null  float64
 6   salutation                    30000 non-null  float64
 7   state                         30000 non-null  float64
 8   deliveryTime                  30000 non-null  int64
 9   ageOfAccountUntilTimeOfOrder  30000 non-null  int64
 10  age                           30000 non-null  int64
dtypes: float64(8), int64(3)
memory usage: 2.5 MB
None
returnShipment
0                 15000
1                 15000
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   itemID                        30000 non-null  float64
 1   size                          30000 non-null  float64
 2   color                         30000 non-null  float64
 3   manufacturerID                30000 non-null  float64
 4   price                         30000 non-null  float64
 5   customerID                    30000 non-null  float64
 6   salutation                    30000 non-null  float64
 7   state                         30000 non-null  float64
 8   deliveryTime                  30000 non-null  int64
 9   ageOfAccountUntilTimeOfOrder  30000 non-null  int64
 10  age                           30000 non-null  int64
dtypes: float64(8), int64(3)
memory usage: 2.5 MB
None
returnShipment
0                 15000
1                 15000
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   itemID                        30000 non-null  float64
 1   size                          30000 non-null  float64
 2   color                         30000 non-null  float64
 3   manufacturerID                30000 non-null  float64
 4   price                         30000 non-null  float64
 5   customerID                    30000 non-null  float64
 6   salutation                    30000 non-null  float64
 7   state                         30000 non-null  float64
 8   deliveryTime                  30000 non-null  int64
 9   ageOfAccountUntilTimeOfOrder  30000 non-null  int64
 10  age                           30000 non-null  int64
dtypes: float64(8), int64(3)
memory usage: 2.5 MB
None
returnShipment
0                 15000
1                 15000
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   itemID                        30000 non-null  float64
 1   size                          30000 non-null  float64
 2   color                         30000 non-null  float64
 3   manufacturerID                30000 non-null  float64
 4   price                         30000 non-null  float64
 5   customerID                    30000 non-null  float64
 6   salutation                    30000 non-null  float64
 7   state                         30000 non-null  float64
 8   deliveryTime                  30000 non-null  int64
 9   ageOfAccountUntilTimeOfOrder  30000 non-null  int64
 10  age                           30000 non-null  int64
dtypes: float64(8), int64(3)
memory usage: 2.5 MB
None
returnShipment
0                 15000
1                 15000
dtype: int64
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30000 entries, 0 to 29999
Data columns (total 11 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   itemID                        30000 non-null  float64
 1   size                          30000 non-null  float64
 2   color                         30000 non-null  float64
 3   manufacturerID                30000 non-null  float64
 4   price                         30000 non-null  float64
 5   customerID                    30000 non-null  float64
 6   salutation                    30000 non-null  float64
 7   state                         30000 non-null  float64
 8   deliveryTime                  30000 non-null  int64
 9   ageOfAccountUntilTimeOfOrder  30000 non-null  int64
 10  age                           30000 non-null  int64
dtypes: float64(8), int64(3)
memory usage: 2.5 MB
None
returnShipment
0                 15000
1                 15000
dtype: int64

In [15]:
# Save new datasets
train_one_smote = pd.concat([train_one_X_smote, train_one_y_smote], axis=1)
save_dataset(df=train_one_smote, dataset_type='train', balance=1, technique='snc', encoding='oe')

train_three_smote = pd.concat([train_three_X_smote, train_three_y_smote], axis=1)
save_dataset(df=train_three_smote, dataset_type='train', balance=3, technique='snc', encoding='oe')

train_five_smote = pd.concat([train_five_X_smote, train_five_y_smote], axis=1)
save_dataset(df=train_five_smote, dataset_type='train', balance=5, technique='snc', encoding='oe')

train_twenty_five_smote = pd.concat([train_twenty_five_X_smote, train_twenty_five_y_smote], axis=1)
save_dataset(df=train_twenty_five_smote, dataset_type='train', balance=25, technique='snc', encoding='oe')

train_fifty_smote = pd.concat([train_fifty_X_smote, train_fifty_y_smote], axis=1)
save_dataset(df=train_fifty_smote, dataset_type='train', balance=50, technique='snc', encoding='oe')